version: "3.5"
services:
  app:
    container_name: sis-pm-webserver
    image: sis-pm-webserver:latest-dev
    build:
      context: .
#      args:
#        - PORT=3000
    devices:
#     Set the tight put to device
      - /dev/bus/usb/001
    ports:
      - "3000:3000"